# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(antenna) {transformation: [-0.9993f,0.0368f,0f,-0.608f,0.0368f,0.9993f,0f,0.7769f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(speaker_1) {transformation: [-0.999f,0.0436f,0f,-0.4724f,0.0436f,0.999f,0f,0.3018f,0f,0f,-1f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(speaker_2) {transformation: [-0.999f,0.0436f,0f,0.4642f,0.0436f,0.999f,0f,0.2609f,0f,0f,-1f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display) {transformation: [0.1998f,0.0087f,0f,0.0023f,-0.0087f,0.1998f,0f,0.572f,0f,0f,0.2f,0.2516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(details) {transformation: [-0.999f,0.0436f,0f,0.0475f,0.0436f,0.999f,0f,0.3886f,0f,0f,-1f,0.1953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(stereo) {transformation: [-0.999f,0.0436f,0f,0f,0.0436f,0.999f,0f,0.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}