# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
execute unless data storage animated_java:temp {entry:{data:{rig_hash: 'f6b4f06c88101ee78ac2c3c7d94896774b7fbd77f20b9188a52cb58acc3ec3e9'}}} run function animated_java:global/remove/outdated_rig
function animated_java:music_speaker/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack