# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(antenna) {transformation: [-1f,0f,0f,-0.625f,0f,1f,0f,0.75f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(speaker_1) {transformation: [-1f,0f,0f,-0.4688f,0f,1f,0f,0.2813f,0f,0f,-1f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(speaker_2) {transformation: [-1f,0f,0f,0.4687f,0f,1f,0f,0.2813f,0f,0f,-1f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display) {transformation: [0.2f,0f,0f,-0.0063f,0f,0.2f,0f,0.5719f,0f,0f,0.2f,0.2516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(details) {transformation: [-1f,0f,0f,0.0469f,0f,1f,0f,0.3906f,0f,0f,-1f,0.1953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(stereo) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function animated_java:music_speaker/animations/animation_speaker_beat_1/zzz/frames/0_root_function