id: nbs

data_pack:
    name: nbs-smithed-summit-26-dp
    description: "Data pack for NBS on the Smithed Summit 2026"
    load:
        - data/nbs/module: src
        - data: src/data
    #zipped: true

resource_pack:
    name: nbs-smithed-summit-26-rp
    description: "Resource pack for NBS on the Smithed Summit 2026"
    load: [assets]
    #zipped: true

require: [bolt]
pipeline:
    - src.model
    - mecha
    - src.sound_config
    - src.interaction

output: dist

meta:
    bolt:
        entrypoint: "*"
