data_pack:
  name: nbs-summit26-dp
  description: "OpenNBS at Smithed Summit 2026"

  zipped: true

resource_pack:
  name: nbs-summit26-rp
  description: "OpenNBS at Smithed Summit 2026"

  zipped: true

pipeline:
  - directory: "packages/booth"
    extend: ["beet.yml"]

  - directory: "packages/playback"
    extend: ["beet.yml"]

  - "nbs_shared.plugins.image"
  - "beet.contrib.minify_json"

output: dist
