[project]
name = "nbs-smithed-summit-26"
version = "0.1.0"
description = "Note Block Studio data pack + resource pack for Smithed Summit 2026"
authors = [{ name = "Bentroen", email = "bemcdc@gmail.com" }]
requires-python = ">=3.14,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "beet>=0.115.0,<0.116",
    "pynbs>=1.1.0,<2",
    "bolt>=0.50.1,<0.51",
    "numpy==2.3.2",
    "boto3>=1.38.0,<2",
    "python-dotenv>=1.1.0,<2",
    "pyoxipng>=9.1.1,<10",
    "bolt-selectors>=0.4.0",
]

[dependency-groups]
dev = [
    "snakeviz>=2.2.0,<3",
    "tuna>=0.5.11,<0.6",
]

[tool.uv]
default-groups = "all"
