[project]
name = "nbs-summit26"
version = "0.1.0"
description = "Note Block Studio data pack + resource pack for Smithed Summit 2026"
authors = [{ name = "Bentroen" }]
requires-python = ">=3.14,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]

[dependency-groups]
dev = [
    "poethepoet>=0.37.0",
]

[tool.uv]
default-groups = ["dev"]

[tool.uv.workspace]
members = ["booth", "playback", "shared"]
