# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "animated_java:music_speaker"
data modify storage animated_java:temp entry.data.rig_hash set value "f6b4f06c88101ee78ac2c3c7d94896774b7fbd77f20b9188a52cb58acc3ec3e9"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=animated_java.music_speaker.node.antenna] run function animated_java:music_speaker/zzz/summon/as_node/antenna
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.antenna set from storage animated_java:gu out
execute on passengers if entity @s[tag=animated_java.music_speaker.node.speaker_1] run function animated_java:music_speaker/zzz/summon/as_node/speaker_1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.speaker_1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=animated_java.music_speaker.node.speaker_2] run function animated_java:music_speaker/zzz/summon/as_node/speaker_2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.speaker_2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=animated_java.music_speaker.node.text_display] run function animated_java:music_speaker/zzz/summon/as_node/text_display
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.text_display set from storage animated_java:gu out
execute on passengers if entity @s[tag=animated_java.music_speaker.node.details] run function animated_java:music_speaker/zzz/summon/as_node/details
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.details set from storage animated_java:gu out
execute on passengers if entity @s[tag=animated_java.music_speaker.node.stereo] run function animated_java:music_speaker/zzz/summon/as_node/stereo
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.stereo set from storage animated_java:gu out
function animated_java:music_speaker/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function animated_java:music_speaker/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function animated_java:music_speaker/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new