# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function animated_java:music_speaker/animations/animation_speaker_beat_1/zzz/frames/$(frame) with storage animated_java:temp entry.data.uuids_by_name
return 1