# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.animation_speaker_beat_1.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:music_speaker/animations/animation_speaker_beat_1/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove animated_java.music_speaker.animation.animation_speaker_beat_1.playing