# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(antenna)
$kill $(speaker_1)
$kill $(speaker_2)
$kill $(text_display)
$kill $(details)
$kill $(stereo)