id: nbs

data_pack:
  name: nbs-summit26-booth-dp
  description: "Smithed Summit 2026 OpenNBS booth"

  load: [src]

resource_pack:
  name: nbs-summit26-booth-rp
  description: "Smithed Summit 2026 OpenNBS booth"

  load: [src]

pipeline:
  - src.modules.dialogs
  - src.modules.functions
  - src.modules.globes
  - src.modules.models
  - src.modules.paintings
  - src.modules.textures
  - src.modules.thumbnails
  - beet.contrib.copy_files

meta:
  copy_files:
    resource_pack:
      assets/nbs/textures/block/thumbnails: "../../data/generated/thumbnails/*.png"

output: dist
