# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(antenna) run function animated_java:music_speaker/variants/purple/zzz/apply_to_node_antenna
$execute as $(speaker_1) run function animated_java:music_speaker/variants/purple/zzz/apply_to_node_speaker_1
$execute as $(speaker_2) run function animated_java:music_speaker/variants/purple/zzz/apply_to_node_speaker_2
$execute as $(details) run function animated_java:music_speaker/variants/purple/zzz/apply_to_node_details
$execute as $(stereo) run function animated_java:music_speaker/variants/purple/zzz/apply_to_node_stereo