# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:music_speaker rig_hash set value 'f6b4f06c88101ee78ac2c3c7d94896774b7fbd77f20b9188a52cb58acc3ec3e9'
scoreboard objectives add aj.animation_speaker_playing_120.frame dummy
scoreboard objectives add aj.animation_speaker_beat_1.frame dummy
scoreboard objectives add aj.animation_speaker_beat_2.frame dummy
scoreboard objectives add aj.animation_speaker_beat_3.frame dummy
scoreboard objectives add aj.animation_speaker_beat_4.frame dummy