# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.animation_speaker_playing_120.frame
scoreboard objectives remove aj.animation_speaker_beat_1.frame
scoreboard objectives remove aj.animation_speaker_beat_2.frame
scoreboard objectives remove aj.animation_speaker_beat_3.frame
scoreboard objectives remove aj.animation_speaker_beat_4.frame
tellraw @a [[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (animated_java:music_speaker)'},'\n → '],[{text:'Successfully uninstalled ',color:green},{text:'animated_java:music_speaker',color:yellow},{text:'!'},{text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.',color:gray,italic:true}],'\n']