id: nbs

data_pack:
  name: nbs-summit26-playback-dp
  description: "Smithed Summit 2026 OpenNBS playback system"

  load:
    - data/nbs/module: src

  # Reduce filesystem writes due to song tick functions
  zipped: true

resource_pack:
  name: nbs-summit26-playback-rp
  description: "Smithed Summit 2026 OpenNBS playback system"

require:
  - bolt
  - bolt_selectors

pipeline:
  - mecha
  #- src.sounds

meta:
  bolt:
    entrypoint: "nbs:main"

output: dist
