id: nbs

data_pack:
  name: nbs-summit26-playback-dp
  description: "[DEBUG] Smithed Summit 2026 OpenNBS playback system"

  load:
    - data/nbs/module: src

  zipped: false

resource_pack:
  name: nbs-summit26-playback-rp
  description: "Smithed Summit 2026 OpenNBS playback system"

require:
  - bolt

pipeline:
  - src.config
  - mecha
  #- src.sounds

meta:
  bolt:
    entrypoint: "nbs:main"
  debug: true
  song_manifest_path: "manifest_debug.json"

output: dist
