# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove animated_java.music_speaker.animation.animation_speaker_playing_120.playing
tag @s remove animated_java.music_speaker.animation.animation_speaker_beat_1.playing
tag @s remove animated_java.music_speaker.animation.animation_speaker_beat_2.playing
tag @s remove animated_java.music_speaker.animation.animation_speaker_beat_3.playing
tag @s remove animated_java.music_speaker.animation.animation_speaker_beat_4.playing