[project]
name = "nbs-summit26-booth"
version = "0.1.0"
description = "Note Block Studio booth project for Smithed Summit 2026"
authors = [{ name = "Bentroen" }]
requires-python = ">=3.14,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]
