# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(antenna) {transformation: [-1f,-0.0031f,0f,-0.625f,-0.0031f,1f,0f,0.7485f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(speaker_1) {transformation: [-0.9963f,0f,0f,-0.4688f,0f,0.9963f,0f,0.2798f,0f,0f,-0.9815f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(speaker_2) {transformation: [-0.9963f,0f,0f,0.4687f,0f,0.9963f,0f,0.2798f,0f,0f,-0.9815f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display) {transformation: [0.2f,0f,0f,-0.0063f,0f,0.2f,0f,0.5704f,0f,0f,0.2f,0.2516f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(details) {transformation: [-1f,0f,0f,0.0469f,0f,1f,0f,0.3892f,0f,0f,-1f,0.1953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(stereo) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3735f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}