# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=animated_java.music_speaker.animation.animation_speaker_playing_120.playing] run function animated_java:music_speaker/animations/animation_speaker_playing_120/zzz/on_tick
execute if entity @s[tag=animated_java.music_speaker.animation.animation_speaker_beat_1.playing] run function animated_java:music_speaker/animations/animation_speaker_beat_1/zzz/on_tick
execute if entity @s[tag=animated_java.music_speaker.animation.animation_speaker_beat_2.playing] run function animated_java:music_speaker/animations/animation_speaker_beat_2/zzz/on_tick
execute if entity @s[tag=animated_java.music_speaker.animation.animation_speaker_beat_3.playing] run function animated_java:music_speaker/animations/animation_speaker_beat_3/zzz/on_tick
execute if entity @s[tag=animated_java.music_speaker.animation.animation_speaker_beat_4.playing] run function animated_java:music_speaker/animations/animation_speaker_beat_4/zzz/on_tick
execute on passengers run rotate @s ~ ~